### ISSUE TITLE
Travis stopped building

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#42] opened 2020-04-11 13:52 UTC
At about this commit
https://github.com/jongough/testplugin_pi/commit/1b2973a3cf4d5e3d33d28ff87a4ebda8ddc9d2e9

I haven't figured out why.  Is it the  travis wait?

**Comment by jongough** [comment] 2020-04-11 23:26
The issue is around permissions, who the owner of the job is, etc. When docker is involved the process runs as root, when it is not it runs as the owner of the job stream (not root). So I was just trying to workout how to get things consistent enough to allow the renames/zipping needed.

**Comment by rgleason** [comment] 2020-04-12 00:26
Yes, this makes sense now. Thanks. I'll look to see if I can understand the change. Have made a PR from frontend2_jg branch, fixed some cmakelists.txt conflicts and merged the commits. It is building now.
I left the skeleton TestPlugin code (commented out)  with some big head and foot notes, in hopes it is instructive to others. Mauro can remove it if he wants.

I am a bit puzzled because the cloudsmith  upload seems to be a mix of old squiddio and new. testplugin.  Is this part customized for Mauro, so it is familiar to him and works for his respository setup?

**Comment by rgleason** [comment] 2020-04-12 00:27
I'll close after you comment.

**Comment by jongough** [comment] 2020-04-12 09:37
I think this is fixed with 1.0.67 . All builds have now worked and have created the requisite files in cloudsmith.

**Comment by rgleason** [comment] 2020-04-12 17:42
Lots of effort here to get the right permissions set up. Amazing there are so many ways to express this.
Closing now.

**Closed** 2020-04-12 17:42 UTC
